### PR TITLE
fix(names): change name of xml formatter

### PR DESCRIPTION
**Pull request by Skyppex**
# Changes

- rename: formatters/xmlformat.lua -> formatters/xmlformatter.lua

closes: #571

### CODE REVIEW

**Comment by Skyppex** [comment]
As a note, i was reading the name wrong for the cli program name. That is actually `xmlformat`, but i still think it should be called `xmlformatter` since thats consitent with other popular plugins in the nvim ecosystem (mason.nvim)

**Review by stevearc — CHANGES_REQUESTED** [review]
This is going to break people's configs. Please add a shim like we did in https://github.com/stevearc/conform.nvim/blob/e3263eabbfc1bdbc5b6a60ba8431b64e8dca0a79/lua/conform/formatters/ruff.lua so that `xmlformat` continues to work

**Comment by stevearc** [comment]
That's just because a new version of LuaLS released and added some strictness. I'll fix it on master.

**Comment by Skyppex** [comment]
> That's just because a new version of LuaLS released and added some strictness. I'll fix it on master.

I see, thanks for merging :)
I'm not very versed in the lua ecosystem yet xD

**Pull request merged**
