### PR TITLE
fix(docs): link to `trim_newlines` formatter

### PR DESCRIPTION
**Pull request by nelson137**

### CODE REVIEW

**Review by stevearc — CHANGES_REQUESTED** [review]
These docs are actually autogenerated, you'll need to update the link in the `trim_newlines.lua` file

**Comment by nelson137** [comment]
> These docs are actually autogenerated, you'll need to update the link in the `trim_newlines.lua` file

Ah gotcha, I can do that.

**Comment by nelson137** [comment]
@stevearc done :)

**Comment by stevearc** [comment]
Thanks!

**Pull request merged**
