### PR TITLE
feat: add `markdownlint`, `stylelint`, `codespell`, and `biome`

### PR DESCRIPTION
**Pull request by chrisgrieser**

### CODE REVIEW

**Comment by stevearc** [comment]
Thanks! For the merge conflicts: you don't actually need to update the README. I have a github action that will make sure it's up-to-date.

**Comment by chrisgrieser** [comment]
ah, I see. should I just reset the file?

**Comment by chrisgrieser** [comment]
check failed due to wrong indentation in a file. Pushed a fix

**Comment by stevearc** [comment]
Looks like another merge conflict >.<

You can just ignore the README changes entirely and only commit the new files. The bot will follow up with a commit like ee679d1f71a64b706d53d2acff36dd2c62fc9c6e and add the proper entries.

**Comment by chrisgrieser** [comment]
yeah, the merge conflict came from the fact that you merged a PR with new linters in the meantime :(

anyway, I just resolved the conflict, which should do it

**Comment by stevearc** [comment]
Thanks for the PR!

**Pull request merged**
