### PR TITLE
improve error message for unknown formatters

### PR DESCRIPTION
**Pull request by ro0gr**
This tries to solve the #582. 

I'm not really sure if it makes the feedback noticeably better. But I think with this kind of message I might have noticed my configuration issue earlier.

I'd say it's still missing highlighting the `unavailable` keyword with an error color, cause this kind of error is probably caused by the misconfiguration on the user side, and it makes sense to make it as clear as possible. WDYT?

### CODE REVIEW

**Comment by stevearc** [comment]
This change LGTM. Did you want me to merge or did you want to try to change the highlighting?

**Comment by ro0gr** [comment]
Thanks. Yeah, I'll give a try to highlighting improvements.

**Comment by ro0gr** [comment]
It's ready for review now

**Comment by stevearc** [comment]
LGTM thanks for the PR!

**Pull request merged**
